{
 "title": "高斯详情",
 "tags": [ "openGauss_db" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "instance", "label": "实例", "query": { "query": "label_values(pg_up,instance)" } },
   { "name": "server", "query": { "query": "label_values(pg_up, server)" } }
  ]
 },
 "panels": [
  { "title": "概览", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "系统CPU使用率",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(rate(node_cpu_seconds_total{mode=\"system\"}[2m])) by (instance) *100",
     "legendFormat": "系统使用率"
    },
    {
     "expr": "avg(rate(node_cpu_seconds_total{mode=\"iowait\"}[2m])) by (instance) *100",
     "legendFormat": "磁盘IO使用率"
    },
    {
     "expr": "(1 - avg(rate(node_cpu_seconds_total{mode=\"idle\"}[2m])) by (instance))*100",
     "legendFormat": "总使用率"
    }
   ]
  },
  {
   "title": "内存信息",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "node_memory_MemTotal_bytes", "legendFormat": "总内存" },
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes",
     "legendFormat": "已用"
    },
    { "expr": "node_memory_MemAvailable_bytes", "legendFormat": "可用" },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes/ (node_memory_MemTotal_bytes)))* 100",
     "legendFormat": "使用率"
    }
   ]
  },
  {
   "title": "线程空闲率",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gauss_thread_wait_status_wait_thread_count{server=\"$server\"}/gauss_thread_wait_status_thread_total_count{server=\"$server\"}"
    }
   ]
  },
  {
   "title": "会话空闲率",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gauss_stat_activity_idle_status_counts{server=\"$server\"}/gauss_stat_activity_total_count{server=\"$server\"}"
    }
   ]
  },
  {
   "title": "缓存命中率",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gauss_query_statement_cache_hit_rate{server=\"$server\"}"
    }
   ]
  },
  {
   "title": "共享内存使用率",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gauss_global_shared_memory_detail_usedsize{server=\"$server\",instance=\"$instance\"}/gauss_global_shared_memory_detail_totalsize{server=\"$server\",instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "死锁增长数",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "idelta(pg_stat_database_deadlocks{server=\"$server\"}[1m])",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "冲突增长率",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 6 },
   "targets": [
    {
     "expr": "irate(pg_stat_database_conflicts[5m])",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "全局会话状态统计",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (statname) (gauss_global_session_stat_value)"
    }
   ]
  },
  {
   "title": "数据库连接情况",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_connections_used_conn{server=\"$server\",instance=\"$instance\"}",
     "legendFormat": "已用连接数"
    },
    {
     "expr": "pg_connections_res_for_normal{server=\"$server\",instance=\"$instance\"}",
     "legendFormat": "预留连接数"
    }
   ]
  },
  { "title": "replication", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "日志同步状态",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "pg_stat_replication_sync_priority{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "日志同步位置",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "pg_stat_replication_sent_lsn{instance=\"$instance\"}",
     "legendFormat": "发送端发送日志位置"
    },
    {
     "expr": "pg_stat_replication_flush_lsn{instance=\"$instance\"}",
     "legendFormat": "接收端flush日志位置"
    }
   ]
  },
  { "title": "查询", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "SQL数量分布",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(gauss_workload_sql_count_dcl_count)"
    },
    {
     "expr": "sum(gauss_workload_sql_count_ddl_count)"
    },
    {
     "expr": "sum(gauss_workload_sql_count_dml_count)"
    }
   ]
  },
  {
   "title": "复杂语句统计",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "targets": [
    { "expr": "gauss_complex_count_count" }
   ]
  },
  { "title": "Utility", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "双写文件情况",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "gauss_global_double_write_status_value"
    }
   ]
  },
  {
   "title": "刷页信息和检查点信息",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "gauss_global_pagewriter_status_pgwr_actual_flush_total_num"
    },
    {
     "expr": "gauss_global_pagewriter_status_pgwr_last_flush_num"
    },
    {
     "expr": "gauss_global_pagewriter_status_remain_dirty_page_num"
    }
   ]
  },
  {
   "title": "检查点信息",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 36 },
   "targets": [
    { "expr": "gauss_global_ckpt_status_value" }
   ]
  },
  {
   "title": "用户登录信息统计",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "expr": "gauss_user_login_login_counter{server=\"$server\"}"
    },
    {
     "expr": "gauss_user_login_logout_counter"
    }
   ]
  },
  { "title": "IO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "数据库文件IO块数",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "gauss_summary_file_iostat_total_phyblkrd",
     "legendFormat": "读物理文件块数"
    },
    {
     "expr": "gauss_summary_file_iostat_total_phyblkwrt",
     "legendFormat": "写物理文件块数"
    }
   ]
  },
  {
   "title": "用户关系表IO状态信息",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 41 },
   "targets": [
    { "expr": "gauss_statio_user_tables_value" }
   ]
  },
  { "title": "其他", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "冲突状态统计",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "pg_stat_database_conflicts_confl_bufferpin"
    },
    {
     "expr": "pg_stat_database_conflicts_confl_deadlock"
    },
    {
     "expr": "pg_stat_database_conflicts_confl_lock"
    },
    {
     "expr": "pg_stat_database_conflicts_confl_snapshot"
    },
    {
     "expr": "pg_stat_database_conflicts_confl_tablespace"
    }
   ]
  },
  {
   "title": "数据库扩展信息",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 47 },
   "targets": [
    {
     "expr": "gauss_available_extension_versions_value"
    }
   ]
  },
  {
   "title": "线程日志回放情况",
   "type": "table",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "gauss_redo_stat_value" }
   ]
  },
  {
   "title": "事务锁信息统计",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "sum by (mode) (pg_lock_count{instance=\"$instance\"})",
     "legendFormat": "{{mode}}"
    }
   ]
  }
 ]
}