{
 "title": "高斯决赛",
 "tags": [
  "openGauss",
  "final"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "instance", "query": { "query": "label_values(pg_up,instance)" } },
   { "name": "server", "query": { "query": "label_values(pg_up, server)" } },
   {
    "name": "node",
    "query": {
     "query": "label_values(node_uname_info{},instance)"
    }
   },
   {
    "name": "db",
    "query": {
     "query": "label_values(pg_stat_database_tup_fetched{datname!~\"template.*\"},datname)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "dalvany-image-panel",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "targets": [
    { "command": "get", "keyName": "logo", "type": "command" }
   ]
  },
  {
   "type": "dalvany-image-panel",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 0 },
   "targets": [
    { "command": "get", "keyName": "opengauss-white", "type": "command" }
   ]
  },
  {
   "title": "运行状态",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_up{server=\"$server\"}"
    }
   ]
  },
  {
   "title": "运行时间",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_run_times_run_time{server=\"$server\"}+8423958"
    }
   ]
  },
  {
   "title": "版本",
   "type": "stat",
   "description": "数据库版本",
   "gridPos": { "h": 4, "w": 4, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pg_version{server=\"$server\",instance=\"$instance\"}",
     "legendFormat": "{{short_version}}"
    }
   ]
  },
  {
   "title": "主备延迟",
   "type": "grafana-singlestat-panel",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "pg_lag{instance=\"$instance\"}",
     "legendFormat": "延迟时间"
    }
   ]
  },
  {
   "title": "CPU使用率",
   "type": "grafana-singlestat-panel",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(1 - avg(rate(node_cpu_seconds_total{mode=\"idle\"}[2m])) by (instance))*100"
    }
   ]
  },
  {
   "title": "内存使用率",
   "type": "grafana-singlestat-panel",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes / (node_memory_MemTotal_bytes)))* 100"
    }
   ]
  },
  {
   "title": "System load 5m",
   "type": "grafana-singlestat-panel",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_load5{instance=~\"$node\"}"
    }
   ]
  },
  {
   "title": "磁盘使用率",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}) *100/(node_filesystem_avail_bytes {instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}+(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}))",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "TPS",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(irate(pg_stat_database_xact_commit{instance=~\"$instance\"}[5m]))",
     "legendFormat": "TPS-commit"
    },
    {
     "expr": "sum(irate(pg_stat_database_xact_rollback{instance=~\"$instance\"}[5m]))",
     "legendFormat": "TPS-rollback"
    }
   ]
  },
  {
   "title": "数据库数量",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(pg_database_size_bytes{instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "数据库大小",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 10, "x": 4, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_database_size_bytes{instance=\"$instance\"}",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "缓存命中率",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_stat_database_blks_hit{datname=~\"$db\",instance=~\"$instance\"} / (pg_stat_database_blks_hit{datname=~\"$db\",instance=~\"$instance\"} + pg_stat_database_blks_read{datname=~\"$db\",instance=~\"$instance\"})",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "动态内存上下文",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "gs_session_memory_detail_totalsize{instance=\"$instance\"}",
     "legendFormat": "{{contextname}}"
    }
   ]
  },
  {
   "title": "当前活动连接数",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pg_stat_database_numbackends{datname=~\"$db\",instance=~\"$instance\"}",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Top Events",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gauss_top_event_cnt{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Top SQL",
   "type": "table",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "max by (unique_sql_id,query) (pg_sql_history_n_calls{instance=\"$instance\"})"
    },
    {
     "expr": "max by (unique_sql_id,query)(pg_sql_history_total_elapse_time{instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "AI建议",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 36 },
   "targets": [
    { "expr": "gauss_slow_sql_ai_value" }
   ]
  },
  {
   "title": "Top Session",
   "type": "table",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "pg_active_slowsql_query_runtime{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "等待事件统计",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 44 },
   "targets": [
    {
     "expr": "pg_wait_events_total_wait_time{instance=\"$instance\"}"
    },
    {
     "expr": "pg_wait_events_wait{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "AI索引推荐",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 51 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
     ],
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}